### ISSUE TITLE
Add possible trigger warnings to movies

### ISSUE THREAD

**Issue by sschipke-conga** [sschipke-conga/black-stories-fe#21]
## On the Movie Page:
- [ ] Add a section listing possible triggers (string)

**Comment by sschipke** [comment]
@grchappell Can you ad the link here?

**Comment by grchappell** [comment]
https://docs.google.com/document/d/1bA__5ANLkGq7XHJ06Er_xGr8qh1XQa3worL2Dj9TuFo/edit?usp=sharing <https://docs.google.com/document/d/1bA__5ANLkGq7XHJ06Er_xGr8qh1XQa3worL2Dj9TuFo/edit?usp=sharing>



Garrett Chappell
garrettchappell.com
605.593.7782
