### ISSUE TITLE
Sounder Watch and Trailer Need Updating

### ISSUE THREAD

**Issue by sschipke-conga** [sschipke-conga/black-stories-fe#47]
**Sounder** needs its trailer and watch info updated. Neither is available on YouTube it seems

https://deploy-preview-46--blackstories-dev.netlify.app/movie/42489-sounder

**Comment by grchappell** [comment]
Film link: https://www.youtube.com/watch?v=GMD5Pg-IrTk
Trailer link: https://www.youtube.com/watch?v=ryois6DaxhM
